{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidytext
  version: {{ version|replace("-", "_") }}

source:
  fn: tidytext_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tidytext_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidytext/tidytext_{{ version }}.tar.gz
  sha256: fb2ccb94f16ccfb705eee1dd8ef9e8ad93c861ea61fd50b8f3af7bb25be51d84

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-rlang
    - r-dplyr
    - r-stringr
    - r-hunspell
    - r-broom
    - r-matrix
    - r-tokenizers
    - r-janeaustenr
    - r-purrr >=0.1.1
    - r-stopwords
  run:
    - r-base
    - r-rlang
    - r-dplyr
    - r-stringr
    - r-hunspell
    - r-broom
    - r-matrix
    - r-tokenizers
    - r-janeaustenr
    - r-purrr >=0.1.1
    - r-stopwords

test:
  commands:
    - $R -e "library('tidytext')"           # [not win]
    - "\"%R%\" -e \"library('tidytext')\""  # [win]

about:
  home: http://github.com/juliasilge/tidytext
  license: MIT
  summary: Text mining for word processing and sentiment analysis using 'dplyr', 'ggplot2', and
    other tidy tools.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
