{% set version = '0.1.9' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidytext
  version: {{ version|replace("-", "_") }}

source:
  fn: tidytext_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tidytext_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidytext/tidytext_{{ version }}.tar.gz
  sha256: 0e4438911daa09af8cd622cc21c884ae80b9f40f356f8bb8498410c686787dc2

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-broom
    - r-dplyr
    - r-hunspell
    - r-janeaustenr
    - r-purrr >=0.1.1
    - r-rlang
    - r-stopwords
    - r-stringr
    - r-tokenizers
  run:
    - r-base
    - r-matrix
    - r-broom
    - r-dplyr
    - r-hunspell
    - r-janeaustenr
    - r-purrr >=0.1.1
    - r-rlang
    - r-stopwords
    - r-stringr
    - r-tokenizers

test:
  commands:
    - $R -e "library('tidytext')"           # [not win]
    - "\"%R%\" -e \"library('tidytext')\""  # [win]

about:
  home: http://github.com/juliasilge/tidytext
  license: MIT
  summary: Text mining for word processing and sentiment analysis using 'dplyr', 'ggplot2', and
    other tidy tools.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
