{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidytext
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidytext_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidytext/tidytext_{{ version }}.tar.gz
  sha256: 7d36be1e504f751c33dc2239751a600bd4ff05af24a0b9cdd549aff909778bc5

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-dplyr
    - r-generics
    - r-hunspell
    - r-janeaustenr
    - r-purrr >=0.1.1
    - r-rlang
    - r-stopwords
    - r-stringr
    - r-tokenizers
  run:
    - r-base
    - r-matrix
    - r-dplyr
    - r-generics
    - r-hunspell
    - r-janeaustenr
    - r-purrr >=0.1.1
    - r-rlang
    - r-stopwords
    - r-stringr
    - r-tokenizers

test:
  commands:
    - $R -e "library('tidytext')"           # [not win]
    - "\"%R%\" -e \"library('tidytext')\""  # [win]

about:
  home: http://github.com/juliasilge/tidytext
  license: MIT
  summary: Text mining for word processing and sentiment analysis using 'dplyr', 'ggplot2', and other tidy tools.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tidytext
# Type: Package
# Title: Text Mining using 'dplyr', 'ggplot2', and Other Tidy Tools
# Version: 0.2.2
# Authors@R: c(person("Gabriela", "De Queiroz", role = c("ctb"), email = "gabidequeiroz@gmail.com"), person("Emil", "Hvitfeldt", role = c("ctb"), email = "emilhhvitfeldt@gmail.com"), person("Os", "Keyes", role = c("ctb"), email = "ironholds@gmail.com", comment = c(ORCID = "0000-0001-5196-609X")), person("Kanishka", "Misra", role = c("ctb"), email = "kmisra@purdue.edu"), person("Tim", "Mastny", role = c("ctb"), email = "tim.mastny@gmail.com"), person("Jeff", "Erickson", role = c("ctb"), email = "jeff@erick.so"), person("David", "Robinson", role = c("aut"), email = "admiral.david@gmail.com"), person("Julia", "Silge", role = c("aut", "cre"),  email = "julia.silge@gmail.com",  comment = c(ORCID = "0000-0002-3671-836X")))
# Description: Text mining for word processing and sentiment analysis using 'dplyr', 'ggplot2', and other tidy tools.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: TRUE
# URL: http://github.com/juliasilge/tidytext
# BugReports: http://github.com/juliasilge/tidytext/issues
# RoxygenNote: 6.1.1
# Depends: R (>= 2.10)
# Imports: rlang, dplyr, stringr, hunspell, generics, Matrix, tokenizers, janeaustenr, purrr (>= 0.1.1), methods, stopwords
# Suggests: readr, tidyr, XML, tm, quanteda, knitr, rmarkdown, ggplot2, reshape2, wordcloud, topicmodels, NLP, scales, gutenbergr, testthat, vdiffr, mallet, stm, data.table, broom, textdata
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-07-27 18:53:23 UTC; juliasilge
# Author: Gabriela De Queiroz [ctb], Emil Hvitfeldt [ctb], Os Keyes [ctb] (<https://orcid.org/0000-0001-5196-609X>), Kanishka Misra [ctb], Tim Mastny [ctb], Jeff Erickson [ctb], David Robinson [aut], Julia Silge [aut, cre] (<https://orcid.org/0000-0002-3671-836X>)
# Maintainer: Julia Silge <julia.silge@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-07-29 13:30:02 UTC
