appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: UzaSr2pNCqYA/KwJ6WNa9gKyz5j7NmB8VQz0T6VpzG8D41IUutxERlsPCY1P4JQvTFO0P275fc0yPGYOV0o4fb6n4tmzJhvSlHbk9eS/CM+vj1Vzor8r2EOkuodjXlQ+J9RwJoWfg1PZXLQY5dJ23QxktD5iPqqm8/xzkkN+Dt6NP6WPtnxjYAsA7TON88++o1WMRuCvjmBLaop3N+1FloKQl6ls6lneXOH44dpDRk6So2P629gaZ/sbNIDtk8LTn2G3sJHIw881Xex9HFBDM/q3eyC7cAjvb7cFHetnxecNbTvoJXFCxk8Q2PghUcI7yFsqMvuyrGBmDY+a+HLVBrHHV72AJfpm0j/hOr6fScsDI0kVHey+eWSkObtGlFt0Rx6wNjUkA2jJXl1mqyfekh+eb5+zmi7dvybtadxtY1evAkJb5TUPANpsftncrXcs5VKjF6+yPVB0SAfLG8dtARNDRo/gzi66Rhjh2DINb+xdQ5jv2HqOKs8SkFXlo0km8fGQDzFX3nvztPj9B3l3JH0+WzHvMX9Uv7LTjSkhV+NMrVpVXr6mb6vSJKqKCVpGG6TCu+rnC4m+0xqsJd5DIidSdThvDcrnrrm1TNNYD5tURPKXrD1Pc58KNMB+K/5iMGKG7L1BJo6kA6ozyuKvJdD15F4lrAc11H65o/ezhNM=
conda_forge_output_validation: true
